# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_most_severe_mutation_type": "00_core.ipynb",
         "get_residues": "00_core.ipynb",
         "get_median_residues": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://gpprnd.github.io/poola_be/"

git_url = "https://github.com/gpprnd/poola_be/tree/master/"

def custom_doc_links(name): return None
